export const SET_LOADING_SCREEN = "SET_LOADING_SCREEN";
export const SET_SIDEBAR = "SET_SIDEBAR";
export const SET_FONT_SELECTOR = "SET_FONT_SELECTOR";
export const SET_COLOR_PICKER = "SET_COLOR_PICKER";
