export const SET_LOADING_SCREEN = "SET_LOADING_SCREEN";
export const SET_SIDEBAR = "SET_SIDEBAR";
export const SET_FONT_SELECTOR_OPEN = "SET_FONT_SELECTOR_OPEN";
export const SET_FONT_SELECTOR_SECTION = "SET_FONT_SELECTOR_SECTION";
export const SET_FONT_SELECTOR_CATEGORIES = "SET_FONT_SELECTOR_CATEGORIES";
export const SET_COLOR_PICKER_OPEN = "SET_COLOR_PICKER_OPEN";
export const SET_COLOR_PICKER_SECTION = "SET_COLOR_PICKER_SECTION";
export const SET_FONT_CATEGORY_SELECTOR_OPEN =
  "SET_FONT_CATEGORY_SELECTOR_OPEN";
export const SET_FONT_CATEGORY_SELECTOR_SECTION =
  "SET_FONT_CATEGORY_SELECTOR_SECTION";
