export const SET_VALIDATION_FONT = "SET_VALIDATION_FONT";
export const SET_DEF_FONT_LOADED = "SET_DEF_FONT_LOADED";
export const SET_BODY_FONT_LOCK = "SET_BODY_FONT_LOCK";
export const SET_BODY_FONT_CATEGORIES = "SET_BODY_FONT_CATEGORIES";
export const SET_HEADER_FONT_LOCK = "SET_HEADER_FONT_LOCK";
export const SET_HEADER_FONT_CATEGORIES = "SET_HEADER_FONT_CATEGORIES";
export const SET_PALETTE_LOCK = "SET_PALETTE_LOCK";
export const SET_HERO_IMG_LOCK = "SET_HERO_IMG_LOCK";
